### ISSUE TITLE
Where are these files coming from?

### ISSUE THREAD

**Issue by simon-mueller** [houkama/KrxImpExp-Blender#2]
Hi, I am currently attempting to make the addon work with Blender 2.8+.

I am wondering...where do the files Krx{Asc,3ds,etc.}{Imp,Exp}.py coming from?

I couldn't find any hints in the Makefile or elsewhere.

**Comment by houkama** [comment]
Hi Simon,
they are part of the original Blender addon: http://krximpexp.sourceforge.net/
If you install e.g. the exe for Blender 2.66 (32/64 bit), it will create a directory with all those .py files and a wxImpExpUI.exe binary in your Blender installation / addons folder.
My repository is just the code to compile this wxImpExpUI.exe so that it works with Blender 2.79b, but the rest of the addon is the same as the original. So that's where the python files, sample meshes, locale and help files come from.

You're right that it may be confusing, I should add it to the readme.

**Comment by simon-mueller** [comment]
Are you also interested in getting this addon compatible with newer versions of Blender? I have made some progress, but I am still struggling with the Armature and Bones since I am not well acquainted with the usage of the program itself.

Anyways, check out the devel branch of my fork and let me know.

**Comment by houkama** [comment]
In general I am interested, I just don't know how much time I really have. I may have a look at it in the future.
